### ISSUE TITLE
Analysing monthly data

### ISSUE THREAD

**Issue by Lizzieeeee42** [cran/rtrim#1]
I'm having issues reading in a file to use rTRIM for monthly count data (abundance count per month for several years, each month identified by 1-12).

I am using read_tdf() but get the following error message:

> UK_sparrow1 <- read_tdf("UK_Sparrow1")
Error: 
Expected 3 columns: site<integer> time<integer> count<numeric>

The only monthly example I can find is the skylark example, in which data() is used rather than read_tdf().

Any help very much appreciated!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the DESCRIPTION file for the package authors.
